######################################################################
# Automatically generated by qmake (3.1) Wed May 18 02:45:47 2022
######################################################################

TEMPLATE = app
TARGET = gui
INCLUDEPATH += .
QT += gui widgets

DEFINES += QT_DEPRECATED_WARNINGS

SOURCES += main.cpp
